- name: Configure new relic application name.
  debconf:
    name: newrelic-php5
    question: newrelic-php5/application-name
    value: "{{ new_relic_apm_app_name }}"
    vtype: string

- name: Configure new relic license key
  debconf:
    name: newrelic-php5
    question: newrelic-php5/license-key
    value: "{{ new_relic_apm_license_key }}"
    vtype: string
